<a href="https://colab.research.google.com/github/gamecicn/TF2_Study/blob/main/FT2_tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf
import numpy as np

## Initialization of Tensors

In [ ]:

x = tf.constant(4)
print(x)

x = tf.constant(4.0)
print(x)

x = tf.constant(4, shape=(1,1))
print(x)

x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([[4]], shape=(1, 1), dtype=int32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [13]:
x = tf.constant([[1,2,3], [4,5,6]])
print(x)

x = tf.ones((3,3))
print(x)

x= tf.zeros((2, 3))
print(x)

x = tf.eye(3)
print(x)



tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 2.0928006   1.1391064  -0.30634972]
 [ 0.19390857  0.32864985 -0.11823907]
 [-0.64313483  0.25143167  0.25078747]], shape=(3, 3), dtype=float32)


In [20]:
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

x = tf.random.uniform((1,3), minval=0, maxval = 1)
print(x)

x = tf.range(9)
print(x)

x = tf.range(start=1, limit=10, delta=2)
print(x)

x = tf.cast(x, dtype=tf.float64)

tf.Tensor(
[[-1.502342  -1.1445646  1.8701488]
 [-0.0063512  1.2913731  0.8602331]
 [-2.0158195 -0.2868633  1.858616 ]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.31814826 0.61364996 0.33990014]], shape=(1, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


## Mathematical Operatinos

In [26]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
z = tf.add(x, y)
print(z)

z = tf.subtract(x, y)
print(z)

z = tf.divide(x, y)
print(z)

z = tf.multiply(x, y)
print(z) 

z = tf.tensordot(x, y, axes=1)
# [x1*y1 + x2*y2 + x3*y3]
print(z)

z = tf.reduce_sum(x*y, axis=0)
print(z)

z = x ** 5
print(z)

# martix multipliation
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

z = tf.matmul(x, y)
print(z)

z = x @ y
print(z)



tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor(
[[ 1.2609596   1.5056121   2.5730646  -0.52326816]
 [-3.1146228   4.6924562   3.334421   -0.6406849 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 1.2609596   1.5056121   2.5730646  -0.52326816]
 [-3.1146228   4.6924562   3.334421   -0.6406849 ]], shape=(2, 4), dtype=float32)


## Indexing

In [34]:
x = tf.constant([0 ,1, 1, 2, 3, 1, 2, 3])

print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]
                 ])
print(x[0, :])
print(x[0:2, :])


tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## Reshaping

In [37]:
x = tf.range(9)
print(x)

x = tf.reshape(x, (3, 3))
print(x)

x = tf.transpose(x, perm=[1, 0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
